In [9]:
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [10]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
c = np.array([[[0,1,2],[3,4,5],[6,7,8]]])
print(c)

[[[0 1 2]
  [3 4 5]
  [6 7 8]]]


In [7]:
a = np.array([[1,2,3],[4,5,6]])
print(a+2)
print(a*2)

[[3 4 5]
 [6 7 8]]
[[ 2  4  6]
 [ 8 10 12]]


In [12]:
a = np.array([[0,1,2],[3,4,5]])
b = np.array([[2,0,1],[5,6,4]])
print(b)
print(a+b)
print(a*b)

[[2 0 1]
 [5 6 4]]
[[ 2  1  3]
 [ 8 10  9]]
[[ 0  0  2]
 [15 24 20]]


In [13]:
d = np.array([[1,1],[1,1]])
e = np.array([1,2])
print(d+e)

[[2 3]
 [2 3]]


In [14]:
a = np.array([[0,1,2],[3,4,5]])
print(a.shape)

(2, 3)


In [16]:
a = np.array([0,1,2,3,4,5,6,7])
b = a.reshape(2,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [17]:
d = np.array([[[0,1,2],[3,4,5]],[[5,4,3],[2,1,0]]])
e = d.reshape(-1)
print(e)

[0 1 2 3 4 5 5 4 3 2 1 0]
